runtime: custom
env: flex
entrypoint: bundle exec rackup --port $PORT

env_variables:
  SERVICE_TYPE: 'web'

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances:

includes:
  - secret.yaml
