runtime: ruby
env: flex
entrypoint: bundle exec rackup --port $PORT

env_variables:
  SECRET_KEY_BASE: 'secret key base'

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  # 公開リポジトリでは本当はコミットしちゃいけないけど隠す方法が全く分からない！ まぁ開発環境なので問題なし。
  cloud_sql_instances: test-app-299803:asia-northeast1:test-app-development

includes:
  - secret.yaml
