version: '3'
services:
  database:
    image: postgres:10
    container_name: 'rails-playground'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sample_development
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
