version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.18.0-buster
  ruby:
    docker:
      - image: circleci/ruby:2.6.6
commands:
  build:
    steps:
      - checkout
  yarn_install:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  bundle_install:
    steps:
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
jobs:
  swagger_yaml_validate:
    executor:
      name: node
    steps:
      - build
      - yarn_install
      - run:
          name: Run validate swagger yaml file
          command: yarn run validate:swagger-yml
  rspec:
    executor:
      name: ruby
    steps:
      - build
      - bundle_install
      - run:
          name: Run RSpec
          command: bundle exec rspec
workflows:
  version: 2
  build_and_test:
    jobs:
      - swagger_yaml_validate
      - rspec
