version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:10.18.0-buster
commands:
  build:
    steps:
      - checkout
  yarn_install:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  swagger_yaml_validate:
    executor:
      name: default
    steps:
      - build
      - yarn_install
      - run:
          name: Run validate swagger yaml file
          command: yarn run validate:swagger-yml
workflows:
  version: 2
  build_and_test:
    jobs:
      - swagger_yaml_validate
